

import json
import logging
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# Set up logging
logger = logging.getLogger(__name__)
model_path = "./sft_model"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path)
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)




def validate_input_question(question: str) -> bool:
    """
    Validates the input question for the QA system.
    Returns False if the question is empty or longer than 300 characters.
    Otherwise returns True.
    Logs a warning if the question is skipped due to invalid length.
    """
    if not question or len(question) > 300:
        logging.warning("Question skipped due to invalid length (empty or > 300 characters).")
        return False
    return True

def ask_question(question: str, max_length: int = 100):
    if not validate_input_question(question):
        logger.warning("Invalid question blocked by guardrail.")
        return "Your question is invalid (empty or too long). Please rephrase."

    prompt = f"Question: {question}\nAnswer:"
    output = generator(prompt, max_length=max_length, num_return_sequences=1)
    print(f"\nGenerated output: {output}")
    
    if output and isinstance(output, list) and "generated_text" in output[0]:
        generated_text = output[0]["generated_text"]
        logger.info(f"Generated output: {generated_text}")
        return generated_text
    else:
        logger.error("No output generated by the model.")
        return "Sorry, the model did not produce an answer."

# Example usage
if __name__ == "__main__":
    # Load the dataset
    with open("data/processed/QandA.json", "r", encoding="utf-8") as f:
        data = json.load(f)
    # Extract only the "question" field from each dict
    questions = [item["question"] for item in data if "question" in item]
    for i, q in enumerate(questions):
        result = validate_input_question(q)
        print(f"Test {i+1}: {repr(q)} => {result}")